[package]
edition = "2021"
name = "hello_c"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-global-executor = "2.3.0"
async-std = "1.12.0"
futures-lite = "1.12.0"
lapin = "2.1.1"
